version: "1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
  
  backend:
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres  # Use 'db' instead of 'localhost'
      API_KEY: "EK-utfXc-Vq1QhUf-j355L"
      JWT_SECRET: "mysecret"
    container_name: my-bun-app
    ports:
      - "5010:5000"
    build:
      context: .
      dockerfile: Dockerfile
