name: CI/CD with Server Deployment

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /var/www/bunApp || exit 1

            # Ensure git remote is set up correctly
            git remote add origin git@github.com:TommyEd12/bot_app.git 
            
            git fetch --all --prune
            git reset --hard origin/master || exit 1
            git pull origin master || exit 1

            # Ensure Docker commands work
            docker compose down || exit 1
            docker compose up -d --build || exit 1
